In [9]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [11]:
data = pd.read_csv('pluton.csv')
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

In [25]:
for j, d in enumerate([data, scaled_data]):
    if j == 0:
        print('No standartization')
    else:
        print('With standartization')

    for i in range(1, 11):
        est = KMeans(n_clusters=3, max_iter=i).fit(d)
        
        clusters = [0] * len(est.cluster_centers_)
        for l in range(len(est.cluster_centers_)):
            clusters[l] = np.count_nonzero(est.labels_ == l)

        print('Max iter =', i)
        print(clusters, '\n', est.cluster_centers_)
            


No standartization
Max iter = 1
[24, 15, 6] 
 [[ 0.21195833 75.68516667 20.503       2.65925   ]
 [ 1.38306667 60.63393333 24.38753333  8.66646667]
 [ 1.10666667 70.18466667 18.52033333  7.6705    ]]
Max iter = 2
[15, 24, 6] 
 [[ 1.38306667 60.63393333 24.38753333  8.66646667]
 [ 0.21195833 75.68516667 20.503       2.65925   ]
 [ 1.10666667 70.18466667 18.52033333  7.6705    ]]
Max iter = 3
[15, 24, 6] 
 [[ 1.38306667 60.63393333 24.38753333  8.66646667]
 [ 0.21195833 75.68516667 20.503       2.65925   ]
 [ 1.10666667 70.18466667 18.52033333  7.6705    ]]
Max iter = 4
[24, 15, 6] 
 [[ 0.21195833 75.68516667 20.503       2.65925   ]
 [ 1.38306667 60.63393333 24.38753333  8.66646667]
 [ 1.10666667 70.18466667 18.52033333  7.6705    ]]
Max iter = 5
[24, 15, 6] 
 [[ 0.21195833 75.68516667 20.503       2.65925   ]
 [ 1.38306667 60.63393333 24.38753333  8.66646667]
 [ 1.10666667 70.18466667 18.52033333  7.6705    ]]
Max iter = 6
[24, 15, 6] 
 [[ 0.21195833 75.68516667 20.503       2.65925   